### PR TITLE
Adds a devDependency with a more specific version of shallow compare

### PR DESCRIPTION
**Pull request by danielstreit**
I'm not sure if this is what you meant by `explicit with a devDependency`. Let me know if you had something else in mind.

### CODE REVIEW

**Comment by oliviertassinari** [comment]
Sorry, I meant `peerDependency` for react 😁

**Comment by danielstreit** [comment]
Ok, will update...should it be the same version pattern as the shallow compare?

**Comment by oliviertassinari** [comment]
> should it be the same version pattern as the shallow compare?

`^0.14.0 || ^15.0.0` sounds good 👍

**Comment by danielstreit** [comment]
Created a new pr with just the one commit: https://github.com/oliviertassinari/react-event-listener/pull/16

**Pull request closed without merging**
