### PR TITLE
Match size snapshot in CI with threshold

### PR DESCRIPTION
**Pull request by TrySound**
I added threshold option. Now you can specify maximal difference
between snapshot values.

### CODE REVIEW

**Comment by TrySound** [comment]
Are you okay with threshold option you asked before?

**Comment by oliviertassinari** [comment]
@TrySound This sounds good. Can we keep size-limit (so we are no dependent on rollup)?

**Comment by TrySound** [comment]
But you already depend on it.

**Comment by oliviertassinari** [comment]
@TrySound size-limit pros:
- Accept any entry point. It can be used to evaluate the cost of any arbitrary graph of dependency.
- The output can be investigated with a visual UI.
- Bundler independent. It won't block us from moving from rollup to the next most performant bundler.
- Trust. I have been using size-limit for quite some time. It's reliable.

**Comment by oliviertassinari** [comment]
@TrySound I'm closing the pull request. I hope you can understand why I want to stick to size-limit. Thank you for your time!!!

**Pull request closed without merging**
