### PR TITLE
[core] Reduce bundle size 🚀

### PR DESCRIPTION
**Pull request by oliviertassinari**
From [7.7 kB](https://bundlephobia.com/result?p=react-event-listener@0.5.4) to 1.8 kB.

### CODE REVIEW

**Comment by TrySound** [comment]
It's not quite what I wanted to achieve. Let me make a couple of PRs before merging this.

**Comment by oliviertassinari** [comment]
@TrySound The fix is around inlining the runtime helpers. It should avoid duplicates between babel 6 & babel 7. Also, webpack seems to have an issue with tree-shaking the `babel-runtime/types` modules. This is unrelated to your previous pull-requests. What the link?

**Comment by TrySound** [comment]
@oliviertassinari Duplicating between babel6 and babel7 doesn't matter. Now you duplicate babel7 which could be reused in another lib.

**Comment by oliviertassinari** [comment]
@TrySound Why is the duplication between babel6 and babel7 no an issue? It can happen very quickly:
- https://unpkg.com/@material-ui/core@1.0.0/index.js
- https://unpkg.com/react-scrollbar-size@2.1.0/ScrollbarSize.js

Instead, this PR is following react-transition-group approach:
- https://unpkg.com/react-transition-group@2.3.1/Transition.js

**Comment by oliviertassinari** [comment]
capture d ecran 2018-05-21 a 00 16 26

**Comment by oliviertassinari** [comment]
@TrySound Duplicate still happens, yes indeed. Our only hope is the gzip algo. I also want to update from babel6 to babel7 for transpiling the source. I'm happy to try out another approach, but I think the current approach is a better default than what we had before.
1. It's following the same approach that some of the most used packages in the react ecosystem
2. We stop required babel 6 runtime that duplicate with babel 7 from Material-UI.

The next package to fix is `react-scrollbar-size`. Maybe it's simply a package we should include in Material-UI, with that, we should save 6kb gzipped from the Material-UI bundle.

**Comment by TrySound** [comment]
I'm fixing everything. Take a look at my next PRs. Helpers are good when you know how to use them.

**Comment by TrySound** [comment]
I will take care about `react-scrollbar-size`

**Pull request merged**
