### PR TITLE
rewrite to add various features

### PR DESCRIPTION
**Pull request by jedwards1211**
proper rebase of https://github.com/oliviertassinari/react-event-listener/pull/4

### CODE REVIEW

**Comment by jedwards1211** [comment]
I noticed you have the tests split between two files right now; I kept my tests in the old file.  Is that what you want?

**Comment by oliviertassinari** [comment]
> I noticed you have the tests split between two files right now; I kept my tests in the old file. Is that what you want?

@jedwards1211 Yeah, I'm migrating to use `enzyme` as a test utils. That's fine like this.
Thanks!

**Comment by oliviertassinari** [comment]
Give me some time, I need to do a release now!

**Comment by jedwards1211** [comment]
Cool, thanks!

**Pull request merged**
