### PR TITLE
rewrite to add various features

### PR DESCRIPTION
**Pull request by jedwards1211**
This contains the following features/fixes:

1. Removes old listeners and adds new listeners when its `props` change (this is very important; in the master branch the listeners can get out of sync with what the user has declared if new props get rendered in the component's place)
2. `capture` support (just add a `capture` prop)
3. Not sure why you have the user pass `elementName="window"`; why not just pass an `EventTarget` instance?  (Really this PR tolerates any Object to support IE8).  I changed it to where the user can pass `target={window}`, `target={document}`, `target={document.body}`, etc.  This means if you want you could even listen to an `XMLHttpRequest`, `AudioContext`, etc. with it, which is kind of cool.

Note, I relaxed the ESLint rules; strict rules discourage collaboration and are often inhumane to programmers.  Life is too short for us to sort props by hand, add in dangling commas, etc. just to comply with a linter, when it could be done automatically by a jscodeshift script or IDE.  We are not robots.

I also added Flow checking in the build toolchain.

### CODE REVIEW

**Comment by jedwards1211** [comment]
Ah, my call to `flow` broke the build.  Shoot, I guess I'll just remove it for now.

**Comment by jedwards1211** [comment]
Oh, I had no idea that one can run `eslint --fix` to fix all of the petty errors and warnings, so I'll run that later...

Still, some of the settings I don't like:
* `react/jsx-boolean-value`: `<button disabled/>` is way more elegant than `<button disabled={true}/>`.  I've seen gaearon use props without the `={true}` so I think it's safe to say that the masters prefer that style.
* `react/jsx-sort-props`: this is not as nice as you think, for instance it requires a `max` prop to come before a `min` prop, and why would you want that?  When the order of props reflects the order of the programmer's thoughts, it's clearer to interpret their intention.

**Comment by oliviertassinari** [comment]
@jedwards1211 Hey, sorry for not reviewing this PR sooner, thanks for this PR.
I have some feedback: 
- It would have been better to split this PR into different chunks
- `capture` That's a good idea to add this property 👍
- I don't think that implementing a `shouldComponentUpdate` method is a good idea.
It's increasing the build without speeding up anything. Actually, I'm wondering if this isn't worse.
We loop through the props instead of returning `null`.
- I won't change the eslint rules. The one here are preaty close to the one enforced in `Material-UI` and the one I'm using on all my project.
- If you want to add flow, well, why not :).

**Comment by jedwards1211** [comment]
The `shouldComponentUpdate` isn't to prevent excessive `render` calls, it's to prevent `componentWillUpdate` and `componentDidUpdate` from getting called unnecessarily and removing/adding back the listeners when they haven't changed.  Without `shouldComponentUpdate`, we would be looping through the props twice on each change, once for `componentWillUpdate` and once for `componentDidUpdate` in addition to interacting with the DOM, which would certainly be more work.

Without `componentWillUpdate` and `componentDidUpdate`, as in the current master, there should be a dev mode warning if the props change, because the component wouldn't behave how the user expects.

Does that make sense?

**Comment by oliviertassinari** [comment]
I haven't noticed the `componentDidUpdate` addition. That makes more sense.

**Comment by jedwards1211** [comment]
Not sure why you want to use similar settings to MaterialUI, but at least this is a small project.  Keep in mind though that I wouldn't make large PRs in larger projects if I had to fight with these ESLint rules, since `eslint src --fix` doesn't take care of all of them.

**Comment by jedwards1211** [comment]
Well that's awkward...even for components without state, `shallowCompare` returns `true` if you don't pass the `nextState` argument to it.  Fixed now

**Comment by oliviertassinari** [comment]
> Well that's awkward...even for components without state, shallowCompare returns true if you don't pass the nextState argument to it. Fixed now

Here is the [implementation](https://github.com/facebook/react/blob/master/src/addons/shallowCompare.js#L20) you are right, we need ths `nextState`.
Alright, that looks good to me :). Could you rebase? I will merge, thanks!

**Comment by jedwards1211** [comment]
I'm really not sure I did the rebase right, I haven't rebased before.  I couldn't get it to push until I merged my origin branch, but doesn't that defeat the purpose of a rebase?

**Comment by jedwards1211** [comment]
let me just close this and create a PR with an unmerged rebase branch

**Pull request closed without merging**
