### PR TITLE
[core] Upgrade to Babel 7 + remove polyfills

### PR DESCRIPTION
**Pull request by goto-bus-stop**
Configures the runtime transform to use builtin features instead of
core-js polyfills. See
https://github.com/mui-org/material-ui/issues/11318 for context.

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
Oops, I committed this a while ago and created PR from CLI before checking! :laughing:

**Comment by oliviertassinari** [comment]
We would also need to handle https://github.com/STORIS/react-scrollbar-size. I start to think that this package can be forked and handle internally by Material-UI. As far as I know, we are the only one to use it. cc @TrySound. Also, this package is using `stifle` over `lodash/debounce`. To see if the bundle size is more interesting.

**Comment by TrySound** [comment]
Let's take a look first how owner will behave https://github.com/twobitfool/stifle/pull/1

**Comment by oliviertassinari** [comment]
`stifle` is an alias for `lodash/throttle` not debounce. But I don't think the behavior change matter in the contexts we are using it.

**Comment by TrySound** [comment]
I just wouldn't like to use lodash because it has splitted `lodash-es` package. Hacking package switching sucks.

**Comment by oliviertassinari** [comment]
We are only using lodash for lodash/debounce. I agree it sucks. I have noticed 6 months ago that I was loading 3 times the same lodash modules in my bundle: lodash, lodash/x, lodash.x.

**Comment by twobitfool** [comment]
Just pushed stifle v1.1.0 -- thanks @TrySound.

**Pull request closed without merging**
