### PR TITLE
Prefer named exports

### PR DESCRIPTION
**Pull request by TrySound**
This should fix interop propblem which cjs imports esm.

### CODE REVIEW

**Comment by oliviertassinari** [comment]
Is adding `package.module` support worth changing the import?

**Comment by TrySound** [comment]
Yes. If we still want to achieve treeshakability then everything should be in esm. default exports suck. We should get rid of them.

**Comment by TrySound** [comment]
I didn't write default exports for half year and to be honest I have now a bunch of problems less in my development process.

**Comment by oliviertassinari** [comment]
@TrySound There is almost nothing to tree shake in this component. I disagree.

**Comment by TrySound** [comment]
@oliviertassinari I meant material-ui treeshakability. This package should be treeshakable to not be a dead code in user bundler.

**Comment by TrySound** [comment]
Also with cjs bundle produces bigger bundle.

**Comment by oliviertassinari** [comment]
Sorry, I don't want to sacrifice usability. This diff looks wrong to me:
```diff
-import EventListener from 'react-event-listener';
+import { EventListener } from 'react-event-listener';
```

**Comment by TrySound** [comment]
This look wrong to me. It just doesn't work in our case.
```js
import EventListener, { withOptions } from 'react-event-listener';
```

default exports was added as an interop with cjs. And it doesn't work with cjs as we can see. Named export doesn't make this library unusable. It's just more unified convention. You don't even ask the user to choose the name.

**Comment by oliviertassinari** [comment]
The relevant issue on webpack side: https://github.com/webpack/webpack/issues/6584.

**Pull request closed without merging**
